version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    privileged: true
    restart: always
    ports:
      - '965:80'
    volumes:
      - './nginx/log:/var/log/nginx'
      - './nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf'
      - './html:/usr/share/nginx/html'
    command: /bin/bash -c "nginx -g 'daemon off;'"